/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Todo } from "@prisma/client";

export class TodoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.TodoCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.TodoCountArgs>
  ): Promise<number> {
    return this.prisma.todo.count(args);
  }

  async todos<T extends Prisma.TodoFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TodoFindManyArgs>
  ): Promise<Todo[]> {
    return this.prisma.todo.findMany(args);
  }
  async todo<T extends Prisma.TodoFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TodoFindUniqueArgs>
  ): Promise<Todo | null> {
    return this.prisma.todo.findUnique(args);
  }
  async createTodo<T extends Prisma.TodoCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TodoCreateArgs>
  ): Promise<Todo> {
    return this.prisma.todo.create<T>(args);
  }
  async updateTodo<T extends Prisma.TodoUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TodoUpdateArgs>
  ): Promise<Todo> {
    return this.prisma.todo.update<T>(args);
  }
  async deleteTodo<T extends Prisma.TodoDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TodoDeleteArgs>
  ): Promise<Todo> {
    return this.prisma.todo.delete(args);
  }
}
